/**
 * Definições dos 20 Personagens do Jogo (Personagem 1 até Personagem 20)
 * Visual e figurino Belle Époque / Dark Fantasy inspirados na direção de arte de Clair Obscur: Expedition 33.
 */

export const CHARACTERS = [
  {
    id: 1,
    name: 'Personagem 1',
    title: 'O Duelista da Expedição',
    themeColor: '#0ea5e9',
    secondaryColor: '#0369a1',
    glowColor: 'rgba(14, 165, 233, 0.8)',
    energyColor: '#7dd3fc',
    style: 'Belle Époque Rapier & Fist',
    stats: { health: 1000, speed: 7.2, jumpForce: 13.8, attackPower: 1.05, defense: 1.0 },
    visual: {
      coatType: 'trenchcoat',
      headgear: 'tricorne',
      maskStyle: 'porcelain_half',
      maskColor: '#f8fafc',
      coatColor: '#0f2942',
      accentColor: '#d4af37',
      vestColor: '#1e293b',
      pantColor: '#091522',
      bootColor: '#1c1917',
      gloveColor: '#0284c7',
      paintTrailColor: '#38bdf8'
    },
    description: 'Duelista com sobretudo longo azul-marinho, máscara de porcelana e tricorne clássico.'
  },
  {
    id: 2,
    name: 'Personagem 2',
    title: 'O Alquimista de Tinta',
    themeColor: '#e11d48',
    secondaryColor: '#9f1239',
    glowColor: 'rgba(225, 29, 72, 0.8)',
    energyColor: '#fda4af',
    style: 'Crimson Brawler',
    stats: { health: 1050, speed: 6.8, jumpForce: 13.5, attackPower: 1.15, defense: 1.05 },
    visual: {
      coatType: 'duster',
      headgear: 'fedora',
      maskStyle: 'gilded_plate',
      maskColor: '#e2e8f0',
      coatColor: '#4c0519',
      accentColor: '#fbbf24',
      vestColor: '#2d0612',
      pantColor: '#18181b',
      bootColor: '#271c19',
      gloveColor: '#be123c',
      paintTrailColor: '#f43f5e'
    },
    description: 'Sobretudo carmesim pesado, máscara ornamentada e ataques com rastros incandescentes.'
  },
  {
    id: 3,
    name: 'Personagem 3',
    title: 'A Guardiã do Monólito',
    themeColor: '#a855f7',
    secondaryColor: '#6b21a8',
    glowColor: 'rgba(168, 85, 247, 0.8)',
    energyColor: '#d8b4fe',
    style: 'Phantom Striker',
    stats: { health: 930, speed: 8.2, jumpForce: 14.5, attackPower: 0.95, defense: 0.9 },
    visual: {
      coatType: 'capelet',
      headgear: 'hood',
      maskStyle: 'shadow_veil',
      maskColor: '#f1f5f9',
      coatColor: '#2e1065',
      accentColor: '#c084fc',
      vestColor: '#1e1b4b',
      pantColor: '#0f172a',
      bootColor: '#172554',
      gloveColor: '#9333ea',
      paintTrailColor: '#c084fc'
    },
    description: 'Capuz místico, capa curta de veludo e movimentos de esquiva espectrais.'
  },
  {
    id: 4,
    name: 'Personagem 4',
    title: 'O Colosso de Bronze',
    themeColor: '#d97706',
    secondaryColor: '#92400e',
    glowColor: 'rgba(217, 119, 6, 0.8)',
    energyColor: '#fde68a',
    style: 'Heavy Armored Vanguard',
    stats: { health: 1200, speed: 5.6, jumpForce: 12.8, attackPower: 1.28, defense: 1.2 },
    visual: {
      coatType: 'overcoat',
      headgear: 'gilded_visor',
      maskStyle: 'runic_plate',
      maskColor: '#d4af37',
      coatColor: '#451a03',
      accentColor: '#f59e0b',
      vestColor: '#271708',
      pantColor: '#1c1917',
      bootColor: '#292524',
      gloveColor: '#b45309',
      paintTrailColor: '#f59e0b'
    },
    description: 'Casaca pesada reforçada com ombreiras de bronze e elmo esculpido.'
  },
  {
    id: 5,
    name: 'Personagem 5',
    title: 'O Engenheiro Arcano',
    themeColor: '#10b981',
    secondaryColor: '#047857',
    glowColor: 'rgba(16, 185, 129, 0.8)',
    energyColor: '#a7f3d0',
    style: 'Arcane Machinist',
    stats: { health: 980, speed: 7.0, jumpForce: 13.8, attackPower: 1.05, defense: 1.0 },
    visual: {
      coatType: 'trenchcoat',
      headgear: 'beret',
      maskStyle: 'monocle_visor',
      maskColor: '#e2e8f0',
      coatColor: '#064e3b',
      accentColor: '#34d399',
      vestColor: '#022c22',
      pantColor: '#0f172a',
      bootColor: '#1c1917',
      gloveColor: '#059669',
      paintTrailColor: '#10b981'
    },
    description: 'Sobretudo verde esmeralda com faixas de couro, boina clássica e manoplas rúnicas.'
  },
  {
    id: 6,
    name: 'Personagem 6',
    title: 'O Navegador Etéreo',
    themeColor: '#06b6d4',
    secondaryColor: '#0e7490',
    glowColor: 'rgba(6, 182, 212, 0.8)',
    energyColor: '#a5f3fc',
    style: 'Frostborne Duelist',
    stats: { health: 960, speed: 7.5, jumpForce: 14.0, attackPower: 1.0, defense: 0.95 },
    visual: {
      coatType: 'mantle',
      headgear: 'feather_cap',
      maskStyle: 'porcelain_half',
      maskColor: '#f8fafc',
      coatColor: '#083344',
      accentColor: '#22d3ee',
      vestColor: '#164e63',
      pantColor: '#0c4a6e',
      bootColor: '#0f172a',
      gloveColor: '#0891b2',
      paintTrailColor: '#22d3ee'
    },
    description: 'Manto azul glacial, chapéu com pluma e golpes cortantes com névoa luminosa.'
  },
  {
    id: 7,
    name: 'Personagem 7',
    title: 'O Sentinela Silencioso',
    themeColor: '#f59e0b',
    secondaryColor: '#b45309',
    glowColor: 'rgba(245, 158, 11, 0.8)',
    energyColor: '#fef3c7',
    style: 'Solar Monastic',
    stats: { health: 1020, speed: 6.9, jumpForce: 13.6, attackPower: 1.1, defense: 1.05 },
    visual: {
      coatType: 'duster',
      headgear: 'hood',
      maskStyle: 'full_porcelain',
      maskColor: '#fffbeb',
      coatColor: '#362305',
      accentColor: '#fbbf24',
      vestColor: '#291b07',
      pantColor: '#1c1917',
      bootColor: '#18181b',
      gloveColor: '#d97706',
      paintTrailColor: '#fbbf24'
    },
    description: 'Sobretudo desértico com runas solares, capuz e máscara de porcelana dourada.'
  },
  {
    id: 8,
    name: 'Personagem 8',
    title: 'A Dama de Porcelana',
    themeColor: '#ec4899',
    secondaryColor: '#be185d',
    glowColor: 'rgba(236, 72, 153, 0.8)',
    energyColor: '#fbcfe8',
    style: 'Acrobatic Blade Dancer',
    stats: { health: 910, speed: 8.6, jumpForce: 14.8, attackPower: 0.92, defense: 0.88 },
    visual: {
      coatType: 'capelet',
      headgear: 'feather_cap',
      maskStyle: 'porcelain_half',
      maskColor: '#ffffff',
      coatColor: '#500724',
      accentColor: '#f472b6',
      vestColor: '#2e0817',
      pantColor: '#18181b',
      bootColor: '#1c1917',
      gloveColor: '#db2777',
      paintTrailColor: '#f472b6'
    },
    description: 'Capa curta de seda magenta, chapéu aristocrático e giros acrobáticos letais.'
  },
  {
    id: 9,
    name: 'Personagem 9',
    title: 'O Lorde da Meia-Noite',
    themeColor: '#6366f1',
    secondaryColor: '#4338ca',
    glowColor: 'rgba(99, 102, 241, 0.8)',
    energyColor: '#c7d2fe',
    style: 'Royal Fencer',
    stats: { health: 990, speed: 7.4, jumpForce: 13.9, attackPower: 1.08, defense: 0.98 },
    visual: {
      coatType: 'overcoat',
      headgear: 'tricorne',
      maskStyle: 'monocle_visor',
      maskColor: '#f8fafc',
      coatColor: '#1e1b4b',
      accentColor: '#818cf8',
      vestColor: '#2e1065',
      pantColor: '#0f172a',
      bootColor: '#18181b',
      gloveColor: '#4f46e5',
      paintTrailColor: '#818cf8'
    },
    description: 'Casaca nobre azul-índigo, tricorne bordado a ouro e postura de esgrima clássica.'
  },
  {
    id: 10,
    name: 'Personagem 10',
    title: 'O Penitente da Tinta',
    themeColor: '#64748b',
    secondaryColor: '#334155',
    glowColor: 'rgba(100, 116, 139, 0.8)',
    energyColor: '#cbd5e1',
    style: 'Ironclad Boxer',
    stats: { health: 1150, speed: 6.0, jumpForce: 13.0, attackPower: 1.22, defense: 1.15 },
    visual: {
      coatType: 'trenchcoat',
      headgear: 'gilded_visor',
      maskStyle: 'runic_plate',
      maskColor: '#94a3b8',
      coatColor: '#1e293b',
      accentColor: '#94a3b8',
      vestColor: '#0f172a',
      pantColor: '#090d16',
      bootColor: '#18181b',
      gloveColor: '#475569',
      paintTrailColor: '#94a3b8'
    },
    description: 'Sobretudo acinzentado rústico com manoplas de ferro fundido e elmo blindado.'
  },
  {
    id: 11,
    name: 'Personagem 11',
    title: 'O Rastreador das Brumas',
    themeColor: '#84cc16',
    secondaryColor: '#4d7c0f',
    glowColor: 'rgba(132, 204, 22, 0.8)',
    energyColor: '#d9f99d',
    style: 'Wildwood Skirmisher',
    stats: { health: 970, speed: 7.7, jumpForce: 14.1, attackPower: 1.02, defense: 0.95 },
    visual: {
      coatType: 'duster',
      headgear: 'hood',
      maskStyle: 'shadow_veil',
      maskColor: '#ecfccb',
      coatColor: '#1a2e05',
      accentColor: '#a3e635',
      vestColor: '#142004',
      pantColor: '#1c1917',
      bootColor: '#27272a',
      gloveColor: '#65a30d',
      paintTrailColor: '#a3e635'
    },
    description: 'Duster verde-musgo com capuz de batedor e ataques rápidos envoltos em folhagens etéreas.'
  },
  {
    id: 12,
    name: 'Personagem 12',
    title: 'O Conde Carmim',
    themeColor: '#b91c1c',
    secondaryColor: '#7f1d1d',
    glowColor: 'rgba(185, 28, 28, 0.8)',
    energyColor: '#fca5a5',
    style: 'Vampiric Aristocrat',
    stats: { health: 1040, speed: 7.1, jumpForce: 13.7, attackPower: 1.12, defense: 1.02 },
    visual: {
      coatType: 'mantle',
      headgear: 'tricorne',
      maskStyle: 'porcelain_half',
      maskColor: '#ffffff',
      coatColor: '#450a0a',
      accentColor: '#ef4444',
      vestColor: '#2b0707',
      pantColor: '#18181b',
      bootColor: '#1c1917',
      gloveColor: '#991b1b',
      paintTrailColor: '#ef4444'
    },
    description: 'Manto aristocrático carmim com gola alta e máscara de porcelana refinada.'
  },
  {
    id: 13,
    name: 'Personagem 13',
    title: 'O Mensageiro do Vácuo',
    themeColor: '#7c3aed',
    secondaryColor: '#4c1d95',
    glowColor: 'rgba(124, 58, 237, 0.8)',
    energyColor: '#ddd6fe',
    style: 'Void Assassin',
    stats: { health: 920, speed: 8.4, jumpForce: 14.6, attackPower: 0.98, defense: 0.88 },
    visual: {
      coatType: 'trenchcoat',
      headgear: 'fedora',
      maskStyle: 'shadow_veil',
      maskColor: '#f5f3ff',
      coatColor: '#1e0838',
      accentColor: '#a78bfa',
      vestColor: '#130524',
      pantColor: '#090312',
      bootColor: '#18181b',
      gloveColor: '#6d28d9',
      paintTrailColor: '#a78bfa'
    },
    description: 'Sobretudo roxo-vácuo, chapéu aba larga e rastro de distorções espaciais.'
  },
  {
    id: 14,
    name: 'Personagem 14',
    title: 'O Marechal do Sol',
    themeColor: '#ea580c',
    secondaryColor: '#9a3412',
    glowColor: 'rgba(234, 88, 12, 0.8)',
    energyColor: '#ffedd5',
    style: 'Solar Commander',
    stats: { health: 1080, speed: 6.6, jumpForce: 13.4, attackPower: 1.16, defense: 1.08 },
    visual: {
      coatType: 'overcoat',
      headgear: 'feather_cap',
      maskStyle: 'gilded_plate',
      maskColor: '#fed7aa',
      coatColor: '#431407',
      accentColor: '#fb923c',
      vestColor: '#270c04',
      pantColor: '#1c1917',
      bootColor: '#18181b',
      gloveColor: '#c2410c',
      paintTrailColor: '#fb923c'
    },
    description: 'Casaca militar de gala cor âmbar, ombreiras douradas e postura imponente.'
  },
  {
    id: 15,
    name: 'Personagem 15',
    title: 'A Espreitadora Celeste',
    themeColor: '#0284c7',
    secondaryColor: '#0369a1',
    glowColor: 'rgba(2, 132, 199, 0.8)',
    energyColor: '#bae6fd',
    style: 'Skyborne Lancer',
    stats: { health: 950, speed: 8.0, jumpForce: 14.4, attackPower: 1.0, defense: 0.92 },
    visual: {
      coatType: 'capelet',
      headgear: 'beret',
      maskStyle: 'porcelain_half',
      maskColor: '#f0f9ff',
      coatColor: '#07273b',
      accentColor: '#38bdf8',
      vestColor: '#0c3d59',
      pantColor: '#041824',
      bootColor: '#172554',
      gloveColor: '#0284c7',
      paintTrailColor: '#38bdf8'
    },
    description: 'Capa curta azul-petróleo, boina estilizada e ataques aéreos vertiginosos.'
  },
  {
    id: 16,
    name: 'Personagem 16',
    title: 'O Guardião das Sombras',
    themeColor: '#475569',
    secondaryColor: '#1e293b',
    glowColor: 'rgba(71, 85, 105, 0.8)',
    energyColor: '#e2e8f0',
    style: 'Spectral Brawler',
    stats: { health: 1100, speed: 6.4, jumpForce: 13.2, attackPower: 1.2, defense: 1.1 },
    visual: {
      coatType: 'duster',
      headgear: 'hood',
      maskStyle: 'full_porcelain',
      maskColor: '#f1f5f9',
      coatColor: '#0f172a',
      accentColor: '#cbd5e1',
      vestColor: '#020617',
      pantColor: '#090d16',
      bootColor: '#18181b',
      gloveColor: '#334155',
      paintTrailColor: '#cbd5e1'
    },
    description: 'Sobretudo longo preto-grafite com capuz sombrio e máscara espectral impecável.'
  },
  {
    id: 17,
    name: 'Personagem 17',
    title: 'O Místico da Aurora',
    themeColor: '#eab308',
    secondaryColor: '#a16207',
    glowColor: 'rgba(234, 179, 8, 0.8)',
    energyColor: '#fef08a',
    style: 'Dawnlight Monk',
    stats: { health: 1010, speed: 7.3, jumpForce: 13.8, attackPower: 1.06, defense: 1.0 },
    visual: {
      coatType: 'mantle',
      headgear: 'tricorne',
      maskStyle: 'gilded_plate',
      maskColor: '#fef9c3',
      coatColor: '#3a2d04',
      accentColor: '#facc15',
      vestColor: '#241b02',
      pantColor: '#1c1917',
      bootColor: '#18181b',
      gloveColor: '#ca8a04',
      paintTrailColor: '#facc15'
    },
    description: 'Manto bordado com fios de ouro da aurora e máscara metálica esculpida.'
  },
  {
    id: 18,
    name: 'Personagem 18',
    title: 'O Arauto do Sangue',
    themeColor: '#991b1b',
    secondaryColor: '#450a0a',
    glowColor: 'rgba(153, 27, 27, 0.8)',
    energyColor: '#fecaca',
    style: 'Bloodletter Vanguard',
    stats: { health: 1120, speed: 6.3, jumpForce: 13.1, attackPower: 1.24, defense: 1.12 },
    visual: {
      coatType: 'overcoat',
      headgear: 'gilded_visor',
      maskStyle: 'runic_plate',
      maskColor: '#fee2e2',
      coatColor: '#330808',
      accentColor: '#dc2626',
      vestColor: '#1f0404',
      pantColor: '#18181b',
      bootColor: '#1c1917',
      gloveColor: '#7f1d1d',
      paintTrailColor: '#dc2626'
    },
    description: 'Casaca pesada vinho-escuro reforçada com placas rúnicas e manoplas rubras.'
  },
  {
    id: 19,
    name: 'Personagem 19',
    title: 'O Espectro da Floresta',
    themeColor: '#15803d',
    secondaryColor: '#14532d',
    glowColor: 'rgba(21, 128, 61, 0.8)',
    energyColor: '#bbf7d0',
    style: 'Verdant Striker',
    stats: { health: 960, speed: 7.9, jumpForce: 14.2, attackPower: 1.01, defense: 0.94 },
    visual: {
      coatType: 'trenchcoat',
      headgear: 'feather_cap',
      maskStyle: 'porcelain_half',
      maskColor: '#f0fdf4',
      coatColor: '#052e16',
      accentColor: '#4ade80',
      vestColor: '#021c0d',
      pantColor: '#0f172a',
      bootColor: '#1c1917',
      gloveColor: '#16a34a',
      paintTrailColor: '#4ade80'
    },
    description: 'Sobretudo verde-escuro com chapéu aristocrático emplumado e máscara de marfim.'
  },
  {
    id: 20,
    name: 'Personagem 20',
    title: 'O Mestre da Tinta Primordial',
    themeColor: '#3b82f6',
    secondaryColor: '#1d4ed8',
    glowColor: 'rgba(59, 130, 246, 0.9)',
    energyColor: '#93c5fd',
    style: 'Grand Expedition Master',
    stats: { health: 1060, speed: 7.4, jumpForce: 14.0, attackPower: 1.14, defense: 1.05 },
    visual: {
      coatType: 'duster',
      headgear: 'tricorne',
      maskStyle: 'full_porcelain',
      maskColor: '#ffffff',
      coatColor: '#172554',
      accentColor: '#60a5fa',
      vestColor: '#1e1b4b',
      pantColor: '#0f172a',
      bootColor: '#18181b',
      gloveColor: '#2563eb',
      paintTrailColor: '#60a5fa'
    },
    description: 'Lendário casaco duster com caudas esvoaçantes, máscara de porcelana com runas de tinta e tricorne imperial.'
  }
];

export function getCharacterById(id) {
  return CHARACTERS.find((c) => c.id === Number(id)) || CHARACTERS[0];
}
