/**
 * Personagens Oficiais de Clair Obscur: Expedition 33
 * Elenco da expedição e a entidade do Monólito.
 */

export const EXPEDITION_33_CHARACTERS = [
  {
    id: 101,
    name: 'Gustave',
    image: './assets/expedition33/gustave.png',
    themeColor: '#0ea5e9',
    secondaryColor: '#0369a1',
    glowColor: 'rgba(14, 165, 233, 0.85)',
    energyColor: '#7dd3fc',
    stats: { health: 1000, speed: 7.0, jumpForce: 13.8, attackPower: 1.0, defense: 1.0 },
    superType: 'GUSTAVE_SLAM',
    voiceAbility: 'gustave_ability',
    visual: {
      coatType: 'trenchcoat',
      headgear: 'none',
      hairColor: '#271810',
      hairStyle: 'gustave_curls',
      hasMustache: true,
      maskStyle: 'none',
      coatColor: '#0b1626',
      accentColor: '#d4af37',
      vestColor: '#1a2332',
      pantColor: '#0f172a',
      bootColor: '#1c1917',
      gloveColor: '#1e293b',
      paintTrailColor: '#38bdf8',
      weaponType: 'mechanical_arm',
      hasMechanicalArm: true,
      hasLanceramBlade: true
    },
    description: 'Líder da Expedição 33. Luta com seu braço protético mecânico dourado capaz de sobrecargas elétricas e a lâmina Lanceram.'
  },
  {
    id: 102,
    name: 'Maelle',
    image: './assets/expedition33/maelle.png',
    themeColor: '#38bdf8',
    secondaryColor: '#0284c7',
    glowColor: 'rgba(56, 189, 248, 0.85)',
    energyColor: '#bae6fd',
    stats: { health: 1000, speed: 7.0, jumpForce: 13.8, attackPower: 1.0, defense: 1.0 },
    superType: 'MAELLE_WALTZ',
    visual: {
      coatType: 'capelet',
      headgear: 'none',
      hairColor: '#5c2c16',
      hairStyle: 'high_ponytail',
      hasMustache: false,
      maskStyle: 'porcelain_half',
      coatColor: '#0c2742',
      accentColor: '#d4af37',
      vestColor: '#1e293b',
      pantColor: '#0a192f',
      bootColor: '#0f172a',
      gloveColor: '#0f172a',
      paintTrailColor: '#38bdf8',
      weaponType: 'rapier'
    },
    description: 'Irmã adotiva de Gustave. Especialista em estocadas relâmpago com seu florete de duelo e esquivas acrobáticas.'
  },
  {
    id: 103,
    name: 'Lune',
    image: './assets/expedition33/lune.png',
    themeColor: '#a855f7',
    secondaryColor: '#6b21a8',
    glowColor: 'rgba(168, 85, 247, 0.85)',
    energyColor: '#e9d5ff',
    stats: { health: 1000, speed: 7.0, jumpForce: 13.8, attackPower: 1.0, defense: 1.0 },
    visual: {
      coatType: 'mantle',
      headgear: 'none',
      hairColor: '#09090b',
      hairStyle: 'wavy_side_bangs',
      hasMustache: false,
      hasArmCoils: true,
      hasFaceTattoo: true,
      maskStyle: 'none',
      coatColor: '#1b1035',
      accentColor: '#d4af37',
      vestColor: '#09090b',
      pantColor: '#090312',
      bootColor: '#1e1b4b',
      gloveColor: '#09090b',
      paintTrailColor: '#c084fc',
      weaponType: 'astral_orbs'
    },
    superType: 'LUNE_ELEMENTAL',
    description: 'Pesquisadora dedicada a desvendar a maldição da Pintora. Canaliza orbes astrais, feitiços de luz estelar e prismas de tinta.'
  },
  {
    id: 104,
    name: 'Sciel',
    image: './assets/expedition33/sciel.png',
    themeColor: '#f59e0b',
    secondaryColor: '#b45309',
    glowColor: 'rgba(245, 158, 11, 0.85)',
    energyColor: '#fef3c7',
    stats: { health: 1000, speed: 7.0, jumpForce: 13.8, attackPower: 1.0, defense: 1.0 },
    visual: {
      coatType: 'duster',
      headgear: 'none',
      hairColor: '#3d2314',
      hairStyle: 'messy_bangs',
      hasMustache: false,
      hasSunburstChest: true,
      hasGoldRibbons: true,
      maskStyle: 'none',
      coatColor: '#0b1626',
      accentColor: '#d4af37',
      vestColor: '#172033',
      pantColor: '#0f172a',
      bootColor: '#18181b',
      gloveColor: '#0f172a',
      paintTrailColor: '#fbbf24',
      weaponType: 'dual_curved_blades'
    },
    superType: 'SCIEL_DARK_WAVE',
    description: 'Guerreira errante e serena. Empunha lâminas duplas curvas com precisão fluida, fitas de ouro e a habilidade Lâminas do Destino para desferir golpes críticos devastadores.'
  },
  {
    id: 105,
    name: 'Renoir',
    image: './assets/expedition33/renoir.png',
    themeColor: '#78716c',
    secondaryColor: '#44403c',
    glowColor: 'rgba(120, 113, 108, 0.85)',
    energyColor: '#e7e5e4',
    stats: { health: 1000, speed: 7.0, jumpForce: 13.8, attackPower: 1.0, defense: 1.0 },
    superType: 'RENOIR_FLOWER',
    visual: {
      coatType: 'draped_overcoat',
      headgear: 'none',
      hairColor: '#2b2927',
      hairStyle: 'gentleman_beard',
      hasMustache: true,
      hasCane: true,
      maskStyle: 'none',
      coatColor: '#0a0a0c',
      accentColor: '#94a3b8',
      vestColor: '#1e293b',
      pantColor: '#090808',
      bootColor: '#1c1917',
      gloveColor: '#1c1917',
      paintTrailColor: '#f59e0b',
      weaponType: 'gentleman_cane'
    },
    description: 'Pai de Verso. Traje nobre clássico com sobretudo sobre os ombros, bengala de ferro e ataques impiedosos.'
  },
  {
    id: 106,
    name: 'Verso',
    image: './assets/expedition33/verso.png',
    themeColor: '#6366f1',
    secondaryColor: '#4338ca',
    glowColor: 'rgba(99, 102, 241, 0.85)',
    energyColor: '#c7d2fe',
    stats: { health: 1000, speed: 7.0, jumpForce: 13.8, attackPower: 1.0, defense: 1.0 },
    isVerso: true,
    hasNoSkills: true,
    visual: {
      coatType: 'fur_collar_coat',
      headgear: 'none',
      hairColor: '#18181b',
      hairStyle: 'white_streak_fringe',
      hasMustache: true,
      hasFurCollar: true,
      maskStyle: 'none',
      coatColor: '#09090b',
      accentColor: '#d4af37',
      vestColor: '#18181b',
      pantColor: '#09090b',
      bootColor: '#18181b',
      gloveColor: '#1e1b4b',
      paintTrailColor: '#818cf8',
      weaponType: 'gold_saber'
    },
    description: 'Sobrevivente da 1ª Expedição. Cabelos negros com mecha branca frontal, casaco com gola de pele e sabre dourado cintilante.'
  },
  {
    id: 107,
    name: 'Monoco',
    image: './assets/expedition33/monoco.png',
    themeColor: '#d97706',
    secondaryColor: '#78350f',
    glowColor: 'rgba(217, 119, 6, 0.85)',
    energyColor: '#fef3c7',
    stats: { health: 1000, speed: 7.0, jumpForce: 13.8, attackPower: 1.0, defense: 1.0 },
    visual: {
      coatType: 'stone_shell',
      headgear: 'none',
      hairColor: '#cbd5e1',
      hairStyle: 'white_fur_mane',
      hasMustache: false,
      hasRuneFaceSlab: true,
      hasStaffBell: true,
      maskStyle: 'none',
      coatColor: '#475569',
      accentColor: '#f59e0b',
      vestColor: '#334155',
      pantColor: '#1e293b',
      bootColor: '#0f172a',
      gloveColor: '#d97706',
      paintTrailColor: '#f59e0b',
      weaponType: 'gestral_staff',
      isMonoco: true
    },
    superType: 'MONOCO_PARRY_MIMIC',
    description: 'Gestral guardião. Habilidade Turbilhão com cajado (Garen E/Wukong R) com mobilidade e parry mimético refletor de habilidades.'
  },
  {
    id: 109,
    name: 'La Peintresse',
    image: './assets/expedition33/la_peintresse.png',
    themeColor: '#fbbf24',
    secondaryColor: '#d97706',
    glowColor: 'rgba(251, 191, 36, 0.95)',
    energyColor: '#ffffff',
    stats: { health: 1000, speed: 7.0, jumpForce: 13.8, attackPower: 1.0, defense: 1.0 },
    visual: {
      coatType: 'baroque_gown',
      headgear: 'halo_mask',
      hairColor: '#09090b',
      hairStyle: 'baroque_updo',
      hasMustache: false,
      maskStyle: 'full_porcelain_halo',
      coatColor: '#09090b',
      accentColor: '#fbbf24',
      vestColor: '#18181b',
      pantColor: '#09090b',
      bootColor: '#09090b',
      gloveColor: '#fbbf24',
      paintTrailColor: '#fbbf24',
      weaponType: 'colossal_brush',
      isPaintress: true
    },
    superType: 'PAINTRESS_CHROMATIC_WAVES',
    description: 'A deusa misteriosa que acorda a cada ano para pintar um número no Monólito e apagar toda uma geração. Luta com um pincel monumental e arcos de tinta viva.'
  },
  {
    id: 110,
    name: 'Batman',
    image: './assets/expedition33/batman.jpg',
    themeColor: '#38bdf8',
    secondaryColor: '#0f172a',
    glowColor: 'rgba(56, 189, 248, 0.85)',
    energyColor: '#e2e8f0',
    stats: { health: 1000, speed: 7.0, jumpForce: 13.8, attackPower: 1.0, defense: 1.0 },
    superType: 'BATMAN_BATMOBILE',
    visual: {
      coatType: 'capelet',
      headgear: 'bat_cowl',
      hairColor: '#09090b',
      hairStyle: 'none',
      hasMustache: false,
      maskStyle: 'bat_cowl',
      coatColor: '#09090b',
      accentColor: '#38bdf8',
      vestColor: '#1e293b',
      pantColor: '#0f172a',
      bootColor: '#09090b',
      gloveColor: '#0f172a',
      paintTrailColor: '#38bdf8',
      weaponType: 'batarang'
    },
    description: 'O Cavaleiro das Trevas de Gotham adaptado à expedição. Luta com artes marciais furtivas, batarangues e atropela com o Batmóvel enquanto salta com um mortal acrobático.'
  },
  {
    id: 111,
    name: 'Darth Vader',
    image: './assets/expedition33/darth_vader.jpg',
    themeColor: '#ef4444',
    secondaryColor: '#09090b',
    glowColor: 'rgba(239, 68, 68, 0.9)',
    energyColor: '#fca5a5',
    stats: { health: 1000, speed: 7.0, jumpForce: 13.8, attackPower: 1.0, defense: 1.0 },
    superType: 'VADER_CHOKE',
    visual: {
      coatType: 'draped_overcoat',
      headgear: 'sith_helmet',
      hairColor: '#09090b',
      hairStyle: 'none',
      hasMustache: false,
      maskStyle: 'sith_respirator',
      coatColor: '#050505',
      accentColor: '#ef4444',
      vestColor: '#18181b',
      pantColor: '#09090b',
      bootColor: '#050505',
      gloveColor: '#18181b',
      paintTrailColor: '#ef4444',
      weaponType: 'sith_lightsaber'
    },
    description: 'O temido Lorde Sith empunhando seu sabre de luz escarlate e canalizando a Força para estrangular e arremessar seus inimigos.'
  },
  {
    id: 112,
    name: 'Palpatine',
    image: './assets/expedition33/palpatine.jpg',
    themeColor: '#a855f7',
    secondaryColor: '#18181b',
    glowColor: 'rgba(168, 85, 247, 0.9)',
    energyColor: '#c084fc',
    stats: { health: 1000, speed: 7.0, jumpForce: 13.8, attackPower: 1.0, defense: 1.0 },
    superType: 'PALPATINE_DUAL_SABERS',
    visual: {
      coatType: 'mantle',
      headgear: 'hood',
      hairColor: '#e2e8f0',
      hairStyle: 'none',
      hasMustache: false,
      maskStyle: 'shadow_veil',
      coatColor: '#18181b',
      accentColor: '#a855f7',
      vestColor: '#09090b',
      pantColor: '#09090b',
      bootColor: '#09090b',
      gloveColor: '#3b0764',
      paintTrailColor: '#c084fc',
      weaponType: 'force_lightning'
    },
    description: 'O Imperador das Sombras conjurando torrentes de raios da Força e desferindo um violento turbilhão com dois sabres de luz soltando faíscas no chão.'
  },
  {
    id: 113,
    name: 'Coringa',
    image: './assets/expedition33/coringa.jpg',
    themeColor: '#10b981',
    secondaryColor: '#7c3aed',
    glowColor: 'rgba(16, 185, 129, 0.85)',
    energyColor: '#f43f5e',
    stats: { health: 1000, speed: 7.0, jumpForce: 13.8, attackPower: 1.0, defense: 1.0 },
    superType: 'JOKER_GRAND_FINALE',
    visual: {
      coatType: 'trenchcoat',
      headgear: 'fedora',
      hairColor: '#16a34a',
      hairStyle: 'messy_bangs',
      hasMustache: false,
      maskStyle: 'clown_smile',
      coatColor: '#581c87',
      accentColor: '#10b981',
      vestColor: '#047857',
      pantColor: '#3b0764',
      bootColor: '#18181b',
      gloveColor: '#7c3aed',
      paintTrailColor: '#10b981',
      weaponType: 'clown_cards'
    },
    description: 'O Palhaço do Crime com Cartas do Caos cortantes em leque e Gran Finale: revólver BANG! com dinamite surpresa e nuvem de gás tóxico.'
  },
  {
    id: 114,
    name: 'Jack Sparrow',
    image: './assets/expedition33/jack_sparrow.jpg',
    themeColor: '#f59e0b',
    secondaryColor: '#78350f',
    glowColor: 'rgba(245, 158, 11, 0.85)',
    energyColor: '#fef3c7',
    stats: { health: 1000, speed: 7.0, jumpForce: 13.8, attackPower: 1.0, defense: 1.0 },
    superType: 'SPARROW_BLACK_PEARL',
    visual: {
      coatType: 'duster',
      headgear: 'tricorne',
      hairColor: '#291b07',
      hairStyle: 'messy_bangs',
      hasMustache: true,
      maskStyle: 'pirate_bandana',
      coatColor: '#451a03',
      accentColor: '#f59e0b',
      vestColor: '#291b07',
      pantColor: '#1c1917',
      bootColor: '#18181b',
      gloveColor: '#78350f',
      paintTrailColor: '#fbbf24',
      weaponType: 'pirate_saber'
    },
    description: 'Capitão Jack Sparrow bebendo rum para esquivas imprevisíveis e bombardeando a arena com salvas de canhão periódicas do Pérola Negra.'
  },
  {
    id: 115,
    name: 'Relâmpago McQueen',
    image: './assets/expedition33/relampago_mcqueen.jpg',
    themeColor: '#ef4444',
    secondaryColor: '#facc15',
    glowColor: 'rgba(239, 68, 68, 0.95)',
    energyColor: '#fde047',
    stats: { health: 1000, speed: 7.0, jumpForce: 13.8, attackPower: 1.0, defense: 1.0 },
    superType: 'MCQUEEN_KACHOW_BLITZ',
    voiceAbility: 'mcqueen_katchau',
    visual: {
      isVehicle: true,
      isMcQueen: true,
      coatType: 'overcoat',
      headgear: 'racer_cap',
      hairColor: '#facc15',
      hairStyle: 'none',
      hasMustache: false,
      maskStyle: 'visor_95',
      coatColor: '#b91c1c',
      accentColor: '#facc15',
      vestColor: '#7f1d1d',
      pantColor: '#18181b',
      bootColor: '#991b1b',
      gloveColor: '#dc2626',
      paintTrailColor: '#facc15',
      weaponType: 'turbo_thrust'
    },
    description: 'O lendário número 95 da Copa Pistão em sua forma autêntica de carro de corrida, queimando pneus com drift e atropelando tudo no Ka-Chow Blitz!'
  },
  {
    id: 116,
    name: 'Gandalf',
    title: 'O Mago Branco',
    image: './assets/expedition33/gandalf.jpg',
    themeColor: '#f8fafc',
    secondaryColor: '#94a3b8',
    glowColor: 'rgba(248, 250, 252, 0.95)',
    energyColor: '#e2e8f0',
    stats: { health: 1000, speed: 6.8, jumpForce: 13.8, attackPower: 1.05, defense: 1.0 },
    superType: 'GANDALF_SHALL_NOT_PASS',
    hasRangedKick: true,
    visual: {
      coatType: 'mantle',
      headgear: 'wizard_hat',
      hairColor: '#ffffff',
      hairStyle: 'long_beard',
      hasMustache: true,
      maskStyle: 'white_beard',
      coatColor: '#f1f5f9',
      accentColor: '#cbd5e1',
      vestColor: '#e2e8f0',
      pantColor: '#cbd5e1',
      bootColor: '#64748b',
      gloveColor: '#94a3b8',
      paintTrailColor: '#ffffff',
      weaponType: 'istari_staff'
    },
    description: 'O Mago Branco dos Istari. Um dos raros combatentes com projétil mágico no chute (K), cajado de luz divina e a fúria "You Shall Not Pass!".'
  },
  {
    id: 117,
    name: 'Arqueiro Verde',
    title: 'O Arqueiro Esmeralda',
    image: './assets/expedition33/green_arrow.jpg',
    themeColor: '#22c55e',
    secondaryColor: '#15803d',
    glowColor: 'rgba(34, 197, 94, 0.9)',
    energyColor: '#86efac',
    stats: { health: 1000, speed: 7.2, jumpForce: 14.0, attackPower: 1.0, defense: 0.95 },
    superType: 'ARROW_STORM',
    hasRangedKick: true,
    visual: {
      coatType: 'capelet',
      headgear: 'hood',
      hairColor: '#eab308',
      hairStyle: 'short',
      hasMustache: true,
      maskStyle: 'domino_mask',
      coatColor: '#166534',
      accentColor: '#4ade80',
      vestColor: '#14532d',
      pantColor: '#052e16',
      bootColor: '#14532d',
      gloveColor: '#16a34a',
      paintTrailColor: '#22c55e',
      weaponType: 'compound_bow'
    },
    description: 'Vigilante de Star City. O arqueiro mestre que dispara flechas velozes no chute (K), flechas especiais no Q e uma tempestade chovendo dos céus.'
  },
  {
    id: 118,
    name: 'Bruce Banner',
    title: 'O Gigante Esmeralda',
    image: './assets/expedition33/hulk.jpg',
    themeColor: '#84cc16',
    secondaryColor: '#4d7c0f',
    glowColor: 'rgba(132, 204, 22, 0.9)',
    energyColor: '#a3e635',
    stats: { health: 850, speed: 6.2, jumpForce: 12.5, attackPower: 0.75, defense: 0.8 },
    superType: 'HULK_TRANSFORMATION',
    isBannerTransform: true,
    visual: {
      coatType: 'lab_coat',
      headgear: 'none',
      hairColor: '#1c1917',
      hairStyle: 'short_messy',
      hasMustache: false,
      maskStyle: 'glasses',
      coatColor: '#e2e8f0',
      accentColor: '#a855f7',
      vestColor: '#334155',
      pantColor: '#581c87',
      bootColor: '#1e293b',
      gloveColor: '#cbd5e1',
      paintTrailColor: '#84cc16'
    },
    description: 'Começa como um pacífico cientista sem poderes. Ao estourar sua fúria na Ultimate, se transforma permanentemente no incrível Hulk até o fim do combate!'
  },
  {
    id: 119,
    name: 'Zorro',
    title: 'A Raposa da Califórnia',
    image: './assets/expedition33/zorro.jpg',
    themeColor: '#f59e0b',
    secondaryColor: '#18181b',
    glowColor: 'rgba(245, 158, 11, 0.9)',
    energyColor: '#fbbf24',
    stats: { health: 1000, speed: 7.4, jumpForce: 14.0, attackPower: 1.15, defense: 0.85 },
    superType: 'ZORRO_MARK_OF_Z',
    cannotBlock: true,
    hasClashParry: true,
    visual: {
      coatType: 'duster',
      headgear: 'cordobes_hat',
      hairColor: '#09090b',
      hairStyle: 'ponytail',
      hasMustache: true,
      maskStyle: 'antifaz',
      coatColor: '#09090b',
      accentColor: '#f59e0b',
      vestColor: '#18181b',
      pantColor: '#09090b',
      bootColor: '#000000',
      gloveColor: '#18181b',
      paintTrailColor: '#fbbf24',
      weaponType: 'fencing_foil'
    },
    description: 'O lendário justiceiro mascarado. Incapaz de defender, mas se atacar no mesmo momento do oponente, anula completamente o golpe rival e grava a marca do Z!'
  },
  {
    id: 120,
    name: 'Aang',
    title: 'O Último Mestre do Ar & Avatar',
    image: './assets/expedition33/aang.png',
    themeColor: '#0ea5e9',
    secondaryColor: '#f97316',
    glowColor: 'rgba(14, 165, 233, 0.95)',
    energyColor: '#fef08a',
    stats: { health: 950, speed: 8.0, jumpForce: 15.0, attackPower: 1.05, defense: 0.9 },
    superType: 'AVATAR_STATE_FOUR_ELEMENTS',
    hasRangedAirSweep: true,
    visual: {
      coatType: 'monk_robe',
      headgear: 'none',
      hairColor: '#000000',
      hairStyle: 'bald_arrow',
      hasMustache: false,
      maskStyle: 'arrow_tattoo',
      coatColor: '#ea580c',
      accentColor: '#fef08a',
      vestColor: '#ea580c',
      pantColor: '#78350f',
      bootColor: '#991b1b',
      gloveColor: '#ea580c',
      paintTrailColor: '#38bdf8',
      weaponType: 'air_glider'
    },
    description: 'O Avatar de todas as quatro nações. Possui golpes distintos para cada elemento: Ar no chute K, Chicote de Água no Q, Chute de Fogo no Q turbinado, Esmagamento de Terra no chão e o devastador Estado Avatar reunindo os 4 elementos na Ultimate!'
  },
  {
    id: 121,
    name: 'Doutor Estranho',
    title: 'O Mago Supremo',
    image: './assets/expedition33/doutor_estranho.jpg',
    themeColor: '#f59e0b',
    secondaryColor: '#dc2626',
    glowColor: 'rgba(245, 158, 11, 0.95)',
    energyColor: '#ea580c',
    stats: { health: 1000, speed: 6.9, jumpForce: 13.8, attackPower: 1.05, defense: 1.0 },
    superType: 'STRANGE_MIRROR_DIMENSION',
    hasSymmetricalPortals: true,
    visual: {
      coatType: 'levitation_cloak',
      headgear: 'none',
      hairColor: '#1e293b',
      hairStyle: 'streaked_temples',
      hasMustache: true,
      maskStyle: 'sorcerer_goatee',
      coatColor: '#dc2626',
      accentColor: '#fbbf24',
      vestColor: '#1d4ed8',
      pantColor: '#1e3a8a',
      bootColor: '#0f172a',
      gloveColor: '#f59e0b',
      paintTrailColor: '#f59e0b',
      weaponType: 'eye_of_agamotto'
    },
    description: 'Mestre das Artes Místicas. Abre portais simétricos permanentes em ambos os lados da arena que APENAS ele pode atravessar, mandatos de Hoggoth no Q e a Dimensão Espelhada na Ultimate!'
  },
  {
    id: 122,
    name: 'Walter White',
    title: 'Heisenberg',
    image: './assets/expedition33/walter_white.png',
    themeColor: '#0284c7',
    secondaryColor: '#334155',
    glowColor: 'rgba(2, 132, 199, 0.9)',
    energyColor: '#38bdf8',
    stats: { health: 920, speed: 6.6, jumpForce: 13.0, attackPower: 1.15, defense: 0.9 },
    superType: 'HEISENBERG_M60_REMOTE',
    visual: {
      coatType: 'windbreaker',
      headgear: 'porkpie_hat',
      hairColor: '#1c1917',
      hairStyle: 'bald_goatee',
      hasMustache: true,
      maskStyle: 'glasses_goatee',
      coatColor: '#3f3f46',
      accentColor: '#38bdf8',
      vestColor: '#166534',
      pantColor: '#27272a',
      bootColor: '#1c1917',
      gloveColor: '#cbd5e1',
      paintTrailColor: '#0284c7'
    },
    description: 'O rei da química e do submundo. Lança o cristal volátil de fulminato de mercúrio ("This is not meth!") no Q e ativa a metralhadora M60 remota automatizada no porta-malas do carro na Ultimate!'
  },
  {
    id: 123,
    name: 'Messi',
    title: 'La Pulga & Campeão do Mundo',
    image: './assets/expedition33/messi.jpg',
    themeColor: '#38bdf8',
    secondaryColor: '#f8fafc',
    glowColor: 'rgba(56, 189, 248, 0.95)',
    energyColor: '#facc15',
    stats: { health: 980, speed: 8.5, jumpForce: 14.5, attackPower: 1.1, defense: 0.9 },
    superType: 'MESSI_GOLDEN_FREE_KICK',
    visual: {
      coatType: 'tracksuit',
      headgear: 'none',
      hairColor: '#451a03',
      hairStyle: 'short_fade',
      hasMustache: true,
      maskStyle: 'messi_beard',
      coatColor: '#38bdf8',
      accentColor: '#f8fafc',
      vestColor: '#f8fafc',
      pantColor: '#000000',
      bootColor: '#facc15',
      gloveColor: '#22c55e',
      paintTrailColor: '#38bdf8',
      weaponType: 'golden_ball'
    },
    description: 'O gênio do futebol mundial. Drible lendário "Ankara Messi" com caneta desconcertante no Q e uma cobrança de falta mágica com curva parabólica dourada no ângulo na Ultimate!'
  },
  {
    id: 124,
    name: 'Capitão Nascimento',
    title: 'Comandante do BOPE',
    image: './assets/expedition33/capitao_nascimento.jpg',
    themeColor: '#09090b',
    secondaryColor: '#dc2626',
    glowColor: 'rgba(220, 38, 38, 0.85)',
    energyColor: '#ef4444',
    stats: { health: 1020, speed: 7.3, jumpForce: 13.8, attackPower: 1.15, defense: 1.05 },
    superType: 'NASCIMENTO_FACA_NA_CAVEIRA',
    visual: {
      coatType: 'tactical_vest',
      headgear: 'bope_beret',
      hairColor: '#18181b',
      hairStyle: 'military_crew',
      hasMustache: false,
      maskStyle: 'tactical_shades',
      coatColor: '#09090b',
      accentColor: '#dc2626',
      vestColor: '#18181b',
      pantColor: '#09090b',
      bootColor: '#000000',
      gloveColor: '#18181b',
      paintTrailColor: '#dc2626',
      weaponType: 'tactical_rifle'
    },
    description: 'Comandante de elite do BOPE. Interrompe golpes com tapa na cara no Q e executa a incursão tática Faca na Caveira com disparos precisos de fuzil na Ultimate!'
  },
  {
    id: 125,
    name: 'Rapunzel',
    title: 'Princesa da Torre Dourada',
    image: './assets/expedition33/rapunzel.png',
    themeColor: '#facc15',
    secondaryColor: '#c084fc',
    glowColor: 'rgba(250, 204, 21, 0.95)',
    energyColor: '#fef08a',
    stats: { health: 950, speed: 7.4, jumpForce: 14.5, attackPower: 1.05, defense: 0.95 },
    superType: 'RAPUNZEL_GOLDEN_HAIR_STORM',
    visual: {
      coatType: 'corset_dress',
      headgear: 'golden_braid',
      hairColor: '#facc15',
      hairStyle: 'golden_braid',
      hasMustache: false,
      maskStyle: 'freckles_smile',
      coatColor: '#9333ea',
      accentColor: '#facc15',
      vestColor: '#c084fc',
      pantColor: '#a855f7',
      bootColor: '#7e22ce',
      gloveColor: '#e9d5ff',
      paintTrailColor: '#facc15',
      weaponType: 'heavy_frying_pan'
    },
    description: 'A jovem princesa de espírito livre. Desfere pancada ensurdecedora com frigideira de ferro no Q e desencadeia o turbilhão de cabelos dourados que cura sua vida e esmaga o rival na Ultimate!'
  },
  {
    id: 126,
    name: 'Capitão América',
    title: 'O Primeiro Vingador',
    image: './assets/expedition33/capitao_america.jpg',
    themeColor: '#2563eb',
    secondaryColor: '#dc2626',
    glowColor: 'rgba(37, 99, 235, 0.9)',
    energyColor: '#ffffff',
    stats: { health: 1050, speed: 7.2, jumpForce: 13.9, attackPower: 1.1, defense: 1.2 },
    superType: 'CAPTAIN_SHIELD_SLAM',
    visual: {
      coatType: 'tactical_suit',
      headgear: 'avenger_helmet',
      hairColor: '#a16207',
      hairStyle: 'short_part',
      hasMustache: false,
      maskStyle: 'star_crest',
      coatColor: '#1d4ed8',
      accentColor: '#ef4444',
      vestColor: '#1e40af',
      pantColor: '#1e3a8a',
      bootColor: '#991b1b',
      gloveColor: '#b91c1c',
      paintTrailColor: '#3b82f6',
      weaponType: 'vibranium_shield'
    },
    description: 'Steve Rogers, o Primeiro Vingador. Defesa de aço com menor dano de bloqueio, arremesso com ricochete de escudo no Q e investida sísmica com Vibranium Slam na Ultimate!'
  },
  {
    id: 127,
    name: 'Naruto Uzumaki',
    title: 'O Sétimo Hokage',
    image: './assets/expedition33/naruto.png',
    themeColor: '#f97316',
    secondaryColor: '#0284c7',
    glowColor: 'rgba(249, 115, 22, 0.95)',
    energyColor: '#38bdf8',
    stats: { health: 980, speed: 8.2, jumpForce: 14.8, attackPower: 1.12, defense: 0.95 },
    superType: 'NARUTO_RASEN_SHURIKEN',
    visual: {
      coatType: 'ninja_tracksuit',
      headgear: 'ninja_headband',
      hairColor: '#eab308',
      hairStyle: 'spiky_blonde',
      hasMustache: false,
      maskStyle: 'whiskers_face',
      coatColor: '#ea580c',
      accentColor: '#38bdf8',
      vestColor: '#09090b',
      pantColor: '#ea580c',
      bootColor: '#0284c7',
      gloveColor: '#09090b',
      paintTrailColor: '#38bdf8',
      weaponType: 'kunai_chakra'
    },
    description: 'O ninja herói de Konoha. Avanço perfurante com Rasengan de vento no Q e convocação de múltiplos clones das sombras para desferir o catastrófico Fuuton Rasen Shuriken na Ultimate!'
  },
  {
    id: 128,
    name: 'Sasuke Uchiha',
    title: 'O Vingador do Clã Uchiha',
    image: './assets/expedition33/sasuke.jpg',
    themeColor: '#6366f1',
    secondaryColor: '#38bdf8',
    glowColor: 'rgba(99, 102, 241, 0.95)',
    energyColor: '#a855f7',
    stats: { health: 970, speed: 8.5, jumpForce: 15.0, attackPower: 1.15, defense: 0.94 },
    superType: 'SASUKE_KIRIN',
    visual: {
      coatType: 'uchiha_robe',
      headgear: 'spiky_sasuke_hair',
      hairColor: '#1e1b4b',
      hairStyle: 'spiky_black',
      hasMustache: false,
      maskStyle: 'sharingan_eye',
      coatColor: '#475569',
      accentColor: '#818cf8',
      vestColor: '#1e1b4b',
      pantColor: '#1e293b',
      bootColor: '#0f172a',
      gloveColor: '#312e81',
      paintTrailColor: '#818cf8',
      weaponType: 'kusanagi_sword'
    },
    description: 'O herdeiro do Sharingan. Dispara avanços elétricos com Chidori perfurante de guarda no Q e convoca a tempestade primordial dos céus com o lendário Kirin na Ultimate!'
  },
  {
    id: 129,
    name: 'Bob Esponja',
    title: 'O Calça Quadrada da Fenda do Biquíni',
    image: './assets/expedition33/bob_esponja.png',
    themeColor: '#eab308',
    secondaryColor: '#ef4444',
    glowColor: 'rgba(234, 179, 8, 0.95)',
    energyColor: '#38bdf8',
    stats: { health: 1020, speed: 7.4, jumpForce: 14.2, attackPower: 1.05, defense: 1.15 },
    superType: 'SPONGEBOB_BUBBLE_SPATULA',
    visual: {
      coatType: 'square_pants',
      headgear: 'sponge_head',
      hairColor: '#ca8a04',
      hairStyle: 'sponge_top',
      hasMustache: false,
      maskStyle: 'sponge_pores',
      coatColor: '#ffffff',
      accentColor: '#ef4444',
      vestColor: '#78350f',
      pantColor: '#78350f',
      bootColor: '#09090b',
      gloveColor: '#fef08a',
      paintTrailColor: '#facc15',
      weaponType: 'golden_spatula'
    },
    description: 'O lendário cozinheiro do Siri Cascudo. Arremessa hambúrgueres de siri giratórios no Q e aprisiona o oponente em uma bolha gigante seguida de turbilhão de espátula na Ultimate!'
  },
  {
    id: 130,
    name: 'Homem de Ferro',
    title: 'O Vingador de Armadura',
    image: './assets/expedition33/homem_de_ferro.jpg',
    themeColor: '#dc2626',
    secondaryColor: '#facc15',
    glowColor: 'rgba(220, 38, 38, 0.95)',
    energyColor: '#38bdf8',
    stats: { health: 1040, speed: 7.6, jumpForce: 14.5, attackPower: 1.14, defense: 1.12 },
    superType: 'IRONMAN_UNIBEAM',
    visual: {
      coatType: 'iron_armor',
      headgear: 'iron_helmet',
      hairColor: '#dc2626',
      hairStyle: 'helmet_plate',
      hasMustache: false,
      maskStyle: 'arc_visor',
      coatColor: '#dc2626',
      accentColor: '#facc15',
      vestColor: '#991b1b',
      pantColor: '#b91c1c',
      bootColor: '#facc15',
      gloveColor: '#facc15',
      paintTrailColor: '#38bdf8',
      weaponType: 'repulsor_gauntlets'
    },
    description: 'Tony Stark com armadura de nanotecnologia. Dispara feixe de plasma repulsor de pulso no Q e descarrega a potência total do Reator Arc com o colossal Unibeam de peito na Ultimate!'
  },
  {
    id: 131,
    name: 'Homem-Aranha',
    title: 'O Amigão da Vizinhança',
    image: './assets/expedition33/homem_aranha.jpg',
    themeColor: '#ef4444',
    secondaryColor: '#2563eb',
    glowColor: 'rgba(239, 68, 68, 0.95)',
    energyColor: '#f8fafc',
    stats: { health: 960, speed: 8.8, jumpForce: 15.6, attackPower: 1.1, defense: 0.96 },
    superType: 'SPIDERMAN_WEB_BARRAGE',
    visual: {
      coatType: 'spider_suit',
      headgear: 'spider_mask',
      hairColor: '#dc2626',
      hairStyle: 'mask_hood',
      hasMustache: false,
      maskStyle: 'spider_eyes',
      coatColor: '#dc2626',
      accentColor: '#2563eb',
      vestColor: '#1d4ed8',
      pantColor: '#1e40af',
      bootColor: '#dc2626',
      gloveColor: '#dc2626',
      paintTrailColor: '#f8fafc',
      weaponType: 'web_shooters'
    },
    description: 'Peter Parker, o acrobático aracnídeo. Lança teia puxadora para voadora aérea veloz no Q e envolve o inimigo em um casulo de teia seguido de queda sísmica na Ultimate!'
  },
  {
    id: 132,
    name: 'Yoshi',
    title: 'O Dinossauro Companheiro',
    image: './assets/expedition33/yoshi.png',
    themeColor: '#22c55e',
    secondaryColor: '#ffffff',
    glowColor: 'rgba(34, 197, 94, 0.95)',
    energyColor: '#ef4444',
    stats: { health: 1010, speed: 8.0, jumpForce: 16.2, attackPower: 1.08, defense: 1.05 },
    superType: 'YOSHI_EGG_BOMBER',
    visual: {
      coatType: 'dino_saddle',
      headgear: 'yoshi_snout',
      hairColor: '#22c55e',
      hairStyle: 'dino_crest',
      hasMustache: false,
      maskStyle: 'dino_cheeks',
      coatColor: '#22c55e',
      accentColor: '#ef4444',
      vestColor: '#ffffff',
      pantColor: '#16a34a',
      bootColor: '#ea580c',
      gloveColor: '#ffffff',
      paintTrailColor: '#22c55e',
      weaponType: 'spotted_egg'
    },
    description: 'O leal dinossauro verde da Ilha dos Yoshis. Arremessa ovos saltitantes e engole com língua elástica no Q, desencadeando um bombardeio aéreo com casca de ovos e Ground Pound na Ultimate!'
  },
  {
    id: 133,
    name: 'Pikachu',
    title: 'O Rato Elétrico de Kanto',
    image: './assets/expedition33/pikachu.png',
    themeColor: '#eab308',
    secondaryColor: '#ef4444',
    glowColor: 'rgba(234, 179, 8, 0.95)',
    energyColor: '#38bdf8',
    stats: { health: 930, speed: 9.0, jumpForce: 15.2, attackPower: 1.16, defense: 0.92 },
    superType: 'PIKACHU_THUNDER_STRIKE',
    visual: {
      coatType: 'electric_fur',
      headgear: 'pikachu_ears',
      hairColor: '#eab308',
      hairStyle: 'pointed_ears',
      hasMustache: false,
      maskStyle: 'red_cheeks',
      coatColor: '#eab308',
      accentColor: '#78350f',
      vestColor: '#ca8a04',
      pantColor: '#eab308',
      bootColor: '#78350f',
      gloveColor: '#ca8a04',
      paintTrailColor: '#facc15',
      weaponType: 'lightning_tail'
    },
    description: 'O ícone elétrico de Pokémon. Ziguezagueia com Ataque Rápido eletrizante no Q e canaliza um devastador Trovão colossal dos céus de 100.000 Volts na Ultimate!'
  },
  {
    id: 134,
    name: 'Sonic the Hedgehog',
    title: 'O Ouriço Mais Rápido do Mundo',
    image: './assets/expedition33/sonic.png',
    themeColor: '#2563eb',
    secondaryColor: '#ef4444',
    glowColor: 'rgba(37, 99, 235, 0.95)',
    energyColor: '#facc15',
    stats: { health: 940, speed: 10.2, jumpForce: 15.8, attackPower: 1.12, defense: 0.92 },
    superType: 'SONIC_SUPER_TRANSFORMATION',
    visual: {
      coatType: 'speed_runner',
      headgear: 'hedgehog_quills',
      hairColor: '#1d4ed8',
      hairStyle: 'sonic_spikes',
      hasMustache: false,
      maskStyle: 'sonic_eyes',
      coatColor: '#1d4ed8',
      accentColor: '#f8fafc',
      vestColor: '#fdba74',
      pantColor: '#1e40af',
      bootColor: '#dc2626',
      gloveColor: '#ffffff',
      paintTrailColor: '#60a5fa',
      weaponType: 'golden_ring'
    },
    description: 'O velocista azul com atitude. Rola em Spin Dash perfurante em alta velocidade no Q e ativa as Esmeraldas do Caos para se transformar em Super Sonic dourado desferindo blitz supersônico na Ultimate!'
  },
  {
    id: 135,
    name: 'Bane',
    title: 'O Quebrador do Morcego',
    image: './assets/expedition33/bane.png',
    themeColor: '#15803d',
    secondaryColor: '#09090b',
    glowColor: 'rgba(21, 128, 61, 0.95)',
    energyColor: '#22c55e',
    stats: { health: 1120, speed: 6.8, jumpForce: 13.5, attackPower: 1.25, defense: 1.25 },
    superType: 'BANE_BACKBREAKER',
    visual: {
      coatType: 'tactical_vest',
      headgear: 'luchador_mask',
      hairColor: '#18181b',
      hairStyle: 'bald_mask',
      hasMustache: false,
      maskStyle: 'venom_tubes',
      coatColor: '#18181b',
      accentColor: '#16a34a',
      vestColor: '#27272a',
      pantColor: '#14532d',
      bootColor: '#09090b',
      gloveColor: '#18181b',
      paintTrailColor: '#22c55e',
      weaponType: 'venom_injector'
    },
    description: 'O colosso de Santa Prisca. Injeta superesteróide Venom aumentando seu ataque e desferindo soco sísmico no Q e ergue o adversário nas mãos para estilhaçar a coluna com o icônico Quebra-Costas na Ultimate!'
  },
  {
    id: 136,
    name: 'Drácula',
    title: 'O Lorde Vampiro da Valáquia',
    image: './assets/expedition33/dracula.jpg',
    themeColor: '#991b1b',
    secondaryColor: '#09090b',
    glowColor: 'rgba(153, 27, 27, 0.95)',
    energyColor: '#ef4444',
    stats: { health: 1000, speed: 7.8, jumpForce: 14.8, attackPower: 1.15, defense: 1.05 },
    superType: 'DRACULA_BLOOD_ECLIPSE',
    visual: {
      coatType: 'vampire_cape',
      headgear: 'widows_peak',
      hairColor: '#09090b',
      hairStyle: 'slick_back_dark',
      hasMustache: false,
      maskStyle: 'pale_vampire',
      coatColor: '#09090b',
      accentColor: '#991b1b',
      vestColor: '#450a0a',
      pantColor: '#09090b',
      bootColor: '#09090b',
      gloveColor: '#ffffff',
      paintTrailColor: '#991b1b',
      weaponType: 'bat_swarm'
    },
    description: 'O soberano da noite imortal. Envia enxame de morcegos carnívoros no Q recuperando vida com o dreno de sangue e invoca o Eclipse de Sangue escuro com asas demoníacas na Ultimate!'
  },
  {
    id: 137,
    name: 'Kirito',
    title: 'O Espadachim Negro',
    image: './assets/expedition33/kirito.png',
    themeColor: '#09090b',
    secondaryColor: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.95)',
    energyColor: '#38bdf8',
    stats: { health: 970, speed: 8.9, jumpForce: 15.4, attackPower: 1.18, defense: 0.95 },
    superType: 'KIRITO_STARBURST_STREAM',
    voiceAbility: 'kirito_starburst',
    visual: {
      coatType: 'black_wyrm_coat',
      headgear: 'kirito_hair',
      hairColor: '#09090b',
      hairStyle: 'bangs_dark',
      hasMustache: false,
      maskStyle: 'focused_gaze',
      coatColor: '#09090b',
      accentColor: '#38bdf8',
      vestColor: '#18181b',
      pantColor: '#09090b',
      bootColor: '#09090b',
      gloveColor: '#18181b',
      paintTrailColor: '#38bdf8',
      weaponType: 'dual_elucidator_dark_repulser'
    },
    description: 'O lendário herói de Aincrad. Desfere corte cruzado supersônico Vorpal Strike no Q e desencadeia a fúria máxima de lâminas duplas com o lendário Starburst Stream de 16 acertos na Ultimate!'
  },
  {
    id: 138,
    name: 'Eren Yeager',
    title: 'O Titã de Ataque',
    image: './assets/expedition33/eren.png',
    themeColor: '#15803d',
    secondaryColor: '#78350f',
    glowColor: 'rgba(21, 128, 61, 0.95)',
    energyColor: '#facc15',
    stats: { health: 1060, speed: 8.2, jumpForce: 15.0, attackPower: 1.2, defense: 1.1 },
    superType: 'EREN_TITAN_ROAR',
    visual: {
      coatType: 'survey_corps_jacket',
      headgear: 'scout_hair',
      hairColor: '#451a03',
      hairStyle: 'parted_brown',
      hasMustache: false,
      maskStyle: 'titan_marks',
      coatColor: '#854d0e',
      accentColor: '#15803d',
      vestColor: '#f8fafc',
      pantColor: '#ffffff',
      bootColor: '#78350f',
      gloveColor: '#78350f',
      paintTrailColor: '#15803d',
      weaponType: 'dmt_blades'
    },
    description: 'O soldado da Tropa de Exploração. Lança ganchos do DMT e lâminas de aço ultra-duro no Q e morde a própria mão para canalizar o raio amarelo sagrado tornando-se o Titã de Ataque na Ultimate!'
  },
  {
    id: 139,
    name: 'Bruce Lee',
    title: 'O Dragão das Artes Marciais',
    image: './assets/expedition33/bruce_lee.jpg',
    themeColor: '#eab308',
    secondaryColor: '#09090b',
    glowColor: 'rgba(234, 179, 8, 0.95)',
    energyColor: '#facc15',
    stats: { health: 950, speed: 9.8, jumpForce: 16.0, attackPower: 1.22, defense: 0.98 },
    superType: 'BRUCE_LEE_DRAGON_FURY',
    visual: {
      coatType: 'yellow_tracksuit',
      headgear: 'bruce_hair',
      hairColor: '#09090b',
      hairStyle: 'mop_top_black',
      hasMustache: false,
      maskStyle: 'fierce_scowl',
      coatColor: '#eab308',
      accentColor: '#09090b',
      vestColor: '#ca8a04',
      pantColor: '#eab308',
      bootColor: '#eab308',
      gloveColor: '#09090b',
      paintTrailColor: '#facc15',
      weaponType: 'nunchaku'
    },
    description: 'O mestre imortal do Jeet Kune Do. Desfere o lendário soco explosivo One-Inch Punch à queima-roupa no Q e gira nunchakus e chutes voadores com o grito do Dragão na Ultimate!'
  },
  {
    id: 140,
    name: 'Son Goku',
    title: 'O Guerreiro Saiyajin da Terra',
    image: './assets/expedition33/goku.png',
    themeColor: '#ea580c',
    secondaryColor: '#2563eb',
    glowColor: 'rgba(234, 88, 12, 0.95)',
    energyColor: '#38bdf8',
    stats: { health: 1020, speed: 9.4, jumpForce: 16.0, attackPower: 1.24, defense: 1.05 },
    superType: 'GOKU_GENKI_DAMA',
    visual: {
      coatType: 'turtle_gi',
      headgear: 'goku_hair',
      hairColor: '#09090b',
      hairStyle: 'saiyan_wild',
      hasMustache: false,
      maskStyle: 'saiyan_eyes',
      coatColor: '#ea580c',
      accentColor: '#1e40af',
      vestColor: '#1d4ed8',
      pantColor: '#ea580c',
      bootColor: '#1e3a8a',
      gloveColor: '#1d4ed8',
      paintTrailColor: '#38bdf8',
      weaponType: 'ki_blast'
    },
    description: 'Son Goku, o lendário protetor da Terra. Dispara feixe de energia concentrada Kamehameha no Q e ergue os braços para reunir a energia de todos os seres vivos na colossal Genki Dama na Ultimate!'
  },
  {
    id: 141,
    name: 'Mestre Yoda',
    title: 'O Grão-Mestre da Ordem Jedi',
    image: './assets/expedition33/yoda.png',
    themeColor: '#15803d',
    secondaryColor: '#78350f',
    glowColor: 'rgba(34, 197, 94, 0.95)',
    energyColor: '#22c55e',
    stats: { health: 960, speed: 9.8, jumpForce: 16.8, attackPower: 1.22, defense: 1.02 },
    superType: 'YODA_FORCE_UNLEASHED',
    visual: {
      coatType: 'jedi_robe',
      headgear: 'yoda_ears',
      hairColor: '#ffffff',
      hairStyle: 'wispy_white',
      hasMustache: false,
      maskStyle: 'ancient_alien',
      coatColor: '#78350f',
      accentColor: '#22c55e',
      vestColor: '#d6d3d1',
      pantColor: '#57534e',
      bootColor: '#44403c',
      gloveColor: '#15803d',
      paintTrailColor: '#22c55e',
      weaponType: 'green_lightsaber'
    },
    description: 'O sábio Grão-Mestre Jedi. Repele e atordoa com poderoso Empurrão da Força no Q e executa uma tempestade acrobática da Forma IV Ataru com seu sabre de luz verde esmeralda na Ultimate!'
  },
  {
    id: 142,
    name: 'Han Solo',
    title: 'O Capitão da Millennium Falcon',
    image: './assets/expedition33/han_solo.jpg',
    themeColor: '#78350f',
    secondaryColor: '#ef4444',
    glowColor: 'rgba(239, 68, 68, 0.95)',
    energyColor: '#ef4444',
    stats: { health: 990, speed: 8.4, jumpForce: 14.5, attackPower: 1.14, defense: 1.0 },
    superType: 'HAN_SOLO_CARPET_BOMB',
    visual: {
      coatType: 'smuggler_vest',
      headgear: 'scoundrel_hair',
      hairColor: '#451a03',
      hairStyle: 'swept_brown',
      hasMustache: false,
      maskStyle: 'cocky_smirk',
      coatColor: '#18181b',
      accentColor: '#dc2626',
      vestColor: '#f8fafc',
      pantColor: '#1e293b',
      bootColor: '#09090b',
      gloveColor: '#78350f',
      paintTrailColor: '#ef4444',
      weaponType: 'blaster_dl44'
    },
    description: 'O contrabandista mais audacioso da galáxia. Atira primeiro com tiro perfurante de blaster DL-44 no Q e aciona um rasante da Millennium Falcon bombardeando o solo da arena na Ultimate!'
  },
  {
    id: 143,
    name: 'Mario',
    title: 'O Super Encanador do Reino dos Cogumelos',
    image: './assets/expedition33/mario.png',
    themeColor: '#dc2626',
    secondaryColor: '#2563eb',
    glowColor: 'rgba(220, 38, 38, 0.95)',
    energyColor: '#f97316',
    stats: { health: 1010, speed: 8.3, jumpForce: 16.5, attackPower: 1.1, defense: 1.05 },
    superType: 'MARIO_FINALE_FIRE',
    visual: {
      coatType: 'plumber_overalls',
      headgear: 'mario_cap',
      hairColor: '#451a03',
      hairStyle: 'cap_brim',
      hasMustache: true,
      maskStyle: 'mario_mustache',
      coatColor: '#dc2626',
      accentColor: '#facc15',
      vestColor: '#1d4ed8',
      pantColor: '#1d4ed8',
      bootColor: '#78350f',
      gloveColor: '#ffffff',
      paintTrailColor: '#f97316',
      weaponType: 'fireball_flower'
    },
    description: 'O herói de macacão vermelho e bigode. Arremessa bolas de fogo saltitantes no Q e desencadeia duas ondas espirais colossais de chamas mágicas (Mario Finale) na Ultimate!'
  },
  {
    id: 144,
    name: 'Wolverine',
    title: 'A Arma X de Adamantium',
    image: './assets/expedition33/wolverine.jpg',
    themeColor: '#eab308',
    secondaryColor: '#2563eb',
    glowColor: 'rgba(234, 179, 8, 0.95)',
    energyColor: '#f8fafc',
    stats: { health: 1050, speed: 8.7, jumpForce: 15.0, attackPower: 1.25, defense: 1.15 },
    superType: 'WOLVERINE_BERSERKER_BARRAGE',
    visual: {
      coatType: 'xmen_suit',
      headgear: 'wolverine_cowl',
      hairColor: '#09090b',
      hairStyle: 'flared_fins',
      hasMustache: false,
      maskStyle: 'adamantium_fangs',
      coatColor: '#eab308',
      accentColor: '#1d4ed8',
      vestColor: '#1e3a8a',
      pantColor: '#1d4ed8',
      bootColor: '#1e3a8a',
      gloveColor: '#1d4ed8',
      paintTrailColor: '#e2e8f0',
      weaponType: 'adamantium_claws'
    },
    description: 'Logan, o mutante selvagem. Regenera passivamente a cada segundo, desfere corte sônico em X perfurando armaduras no Q e entra em Berserker Barrage com retalhamento total na Ultimate!'
  },
  {
    id: 145,
    name: 'Kratos',
    title: 'O Fantasma de Esparta',
    image: './assets/expedition33/kratos.png',
    themeColor: '#dc2626',
    secondaryColor: '#cbd5e1',
    glowColor: 'rgba(220, 38, 38, 0.95)',
    energyColor: '#f97316',
    stats: { health: 1080, speed: 7.7, jumpForce: 14.6, attackPower: 1.22, defense: 1.12 },
    superType: 'KRATOS_SPARTAN_RAGE',
    visual: {
      coatType: 'spartan_harness',
      headgear: 'kratos_bald_beard',
      hairColor: '#18181b',
      hairStyle: 'full_spartan_beard',
      hasMustache: false,
      maskStyle: 'ash_skin_tattoo',
      coatColor: '#78350f',
      accentColor: '#dc2626',
      vestColor: '#cbd5e1',
      pantColor: '#57534e',
      bootColor: '#78350f',
      gloveColor: '#78350f',
      paintTrailColor: '#f97316',
      weaponType: 'blades_of_chaos'
    },
    description: 'O Deus da Guerra de Esparta. Gira as Lâminas do Caos incandescentes com correntes no Q e ativa a Fúria Espartana desferindo golpes brutais que estilhaçam a rocha na Ultimate!'
  },
  {
    id: 146,
    name: 'Venom',
    title: 'O Protetor Letal',
    image: './assets/expedition33/venom.png',
    themeColor: '#09090b',
    secondaryColor: '#f8fafc',
    glowColor: 'rgba(248, 250, 252, 0.95)',
    energyColor: '#f8fafc',
    stats: { health: 1100, speed: 8.5, jumpForce: 15.6, attackPower: 1.22, defense: 1.14 },
    superType: 'VENOM_WE_ARE_VENOM',
    visual: {
      coatType: 'symbiote_suit',
      headgear: 'symbiote_fangs',
      hairColor: '#09090b',
      hairStyle: 'bald_crest',
      hasMustache: false,
      maskStyle: 'venom_white_eyes',
      coatColor: '#09090b',
      accentColor: '#f8fafc',
      vestColor: '#09090b',
      pantColor: '#09090b',
      bootColor: '#09090b',
      gloveColor: '#09090b',
      paintTrailColor: '#f8fafc',
      weaponType: 'symbiote_tendrils'
    },
    description: 'Nós somos Venom! Dispara gavinhas simbióticas perfurantes no Q e avança engolindo e estraçalhando o oponente com sua colossal mandíbula na Ultimate "Nós Somos Venom"!'
  },
  {
    id: 147,
    name: 'Carnificina',
    title: 'O Psicopata Simbionte',
    image: './assets/expedition33/carnificina.png',
    themeColor: '#dc2626',
    secondaryColor: '#09090b',
    glowColor: 'rgba(220, 38, 38, 0.95)',
    energyColor: '#ef4444',
    stats: { health: 1040, speed: 9.3, jumpForce: 16.4, attackPower: 1.25, defense: 1.05 },
    superType: 'CARNAGE_MAXIMUM_CARNAGE',
    visual: {
      coatType: 'crimson_symbiote',
      headgear: 'carnage_crests',
      hairColor: '#dc2626',
      hairStyle: 'tendril_tendrils',
      hasMustache: false,
      maskStyle: 'carnage_black_eyes',
      coatColor: '#dc2626',
      accentColor: '#09090b',
      vestColor: '#b91c1c',
      pantColor: '#dc2626',
      bootColor: '#991b1b',
      gloveColor: '#dc2626',
      paintTrailColor: '#dc2626',
      weaponType: 'symbiote_scythes'
    },
    description: 'Cletus Kasady, pura carnificina vermelha. Transforma os braços em foices e machados cortantes no Q e deflagra uma tempestade explosiva de espinhos carmesim na Ultimate "Carnificina Total"!'
  },
  {
    id: 148,
    name: 'Capitão Pátria',
    title: 'O Super-Herói Número Um da Vought',
    image: './assets/expedition33/homelander.jpg',
    themeColor: '#1d4ed8',
    secondaryColor: '#dc2626',
    glowColor: 'rgba(239, 68, 68, 0.95)',
    energyColor: '#ef4444',
    stats: { health: 1090, speed: 8.8, jumpForce: 16.0, attackPower: 1.24, defense: 1.12 },
    superType: 'HOMELANDER_LASER_EYES',
    visual: {
      coatType: 'vought_cape_suit',
      headgear: 'blonde_slick_quiff',
      hairColor: '#eab308',
      hairStyle: 'slicked_blonde',
      hasMustache: false,
      maskStyle: 'glowing_laser_eyes',
      coatColor: '#1e3a8a',
      accentColor: '#dc2626',
      vestColor: '#1d4ed8',
      pantColor: '#1e3a8a',
      bootColor: '#991b1b',
      gloveColor: '#991b1b',
      paintTrailColor: '#ef4444',
      weaponType: 'laser_eyes'
    },
    description: 'Homelander, o falso salvador absoluto. Dispara rajada mortal de visão a laser no Q e projeta feixes ópticos devastadores que partem a arena ao meio na Ultimate "Eu Posso Fazer o Que Quiser"!'
  }
];

export function getExpeditionCharacterById(id) {
  return EXPEDITION_33_CHARACTERS.find((c) => c.id === Number(id)) || EXPEDITION_33_CHARACTERS[0];
}
