/**
 * Personagens Oficiais de Clair Obscur: Expedition 33
 * Elenco da expedição e a entidade do Monólito.
 */

export const EXPEDITION_33_CHARACTERS = [
  {
    id: 101,
    name: 'Gustave',
    image: './assets/expedition33/gustave.png',
    themeColor: '#0ea5e9',
    secondaryColor: '#0369a1',
    glowColor: 'rgba(14, 165, 233, 0.85)',
    energyColor: '#7dd3fc',
    stats: { health: 1000, speed: 7.0, jumpForce: 13.8, attackPower: 1.0, defense: 1.0 },
    superType: 'GUSTAVE_SLAM',
    voiceAbility: 'gustave_ability',
    visual: {
      coatType: 'trenchcoat',
      headgear: 'none',
      hairColor: '#271810',
      hairStyle: 'gustave_curls',
      hasMustache: true,
      maskStyle: 'none',
      coatColor: '#0b1626',
      accentColor: '#d4af37',
      vestColor: '#1a2332',
      pantColor: '#0f172a',
      bootColor: '#1c1917',
      gloveColor: '#1e293b',
      paintTrailColor: '#38bdf8',
      weaponType: 'mechanical_arm',
      hasMechanicalArm: true,
      hasLanceramBlade: true
    },
    description: 'Líder da Expedição 33. Luta com seu braço protético mecânico dourado capaz de sobrecargas elétricas e a lâmina Lanceram.'
  },
  {
    id: 102,
    name: 'Maelle',
    image: './assets/expedition33/maelle.png',
    themeColor: '#38bdf8',
    secondaryColor: '#0284c7',
    glowColor: 'rgba(56, 189, 248, 0.85)',
    energyColor: '#bae6fd',
    stats: { health: 1000, speed: 7.0, jumpForce: 13.8, attackPower: 1.0, defense: 1.0 },
    superType: 'MAELLE_WALTZ',
    visual: {
      coatType: 'capelet',
      headgear: 'none',
      hairColor: '#5c2c16',
      hairStyle: 'high_ponytail',
      hasMustache: false,
      maskStyle: 'porcelain_half',
      coatColor: '#0c2742',
      accentColor: '#d4af37',
      vestColor: '#1e293b',
      pantColor: '#0a192f',
      bootColor: '#0f172a',
      gloveColor: '#0f172a',
      paintTrailColor: '#38bdf8',
      weaponType: 'rapier'
    },
    description: 'Irmã adotiva de Gustave. Especialista em estocadas relâmpago com seu florete de duelo e esquivas acrobáticas.'
  },
  {
    id: 103,
    name: 'Lune',
    image: './assets/expedition33/lune.png',
    themeColor: '#a855f7',
    secondaryColor: '#6b21a8',
    glowColor: 'rgba(168, 85, 247, 0.85)',
    energyColor: '#e9d5ff',
    stats: { health: 1000, speed: 7.0, jumpForce: 13.8, attackPower: 1.0, defense: 1.0 },
    visual: {
      coatType: 'mantle',
      headgear: 'none',
      hairColor: '#09090b',
      hairStyle: 'wavy_side_bangs',
      hasMustache: false,
      hasArmCoils: true,
      hasFaceTattoo: true,
      maskStyle: 'none',
      coatColor: '#1b1035',
      accentColor: '#d4af37',
      vestColor: '#09090b',
      pantColor: '#090312',
      bootColor: '#1e1b4b',
      gloveColor: '#09090b',
      paintTrailColor: '#c084fc',
      weaponType: 'astral_orbs'
    },
    superType: 'LUNE_ELEMENTAL',
    description: 'Pesquisadora dedicada a desvendar a maldição da Pintora. Canaliza orbes astrais, feitiços de luz estelar e prismas de tinta.'
  },
  {
    id: 104,
    name: 'Sciel',
    image: './assets/expedition33/sciel.png',
    themeColor: '#f59e0b',
    secondaryColor: '#b45309',
    glowColor: 'rgba(245, 158, 11, 0.85)',
    energyColor: '#fef3c7',
    stats: { health: 1000, speed: 7.0, jumpForce: 13.8, attackPower: 1.0, defense: 1.0 },
    visual: {
      coatType: 'duster',
      headgear: 'none',
      hairColor: '#3d2314',
      hairStyle: 'messy_bangs',
      hasMustache: false,
      hasSunburstChest: true,
      hasGoldRibbons: true,
      maskStyle: 'none',
      coatColor: '#0b1626',
      accentColor: '#d4af37',
      vestColor: '#172033',
      pantColor: '#0f172a',
      bootColor: '#18181b',
      gloveColor: '#0f172a',
      paintTrailColor: '#fbbf24',
      weaponType: 'dual_curved_blades'
    },
    superType: 'SCIEL_DARK_WAVE',
    description: 'Guerreira errante e serena. Empunha lâminas duplas curvas com precisão fluida, fitas de ouro e a habilidade Lâminas do Destino para desferir golpes críticos devastadores.'
  },
  {
    id: 105,
    name: 'Renoir',
    image: './assets/expedition33/renoir.png',
    themeColor: '#78716c',
    secondaryColor: '#44403c',
    glowColor: 'rgba(120, 113, 108, 0.85)',
    energyColor: '#e7e5e4',
    stats: { health: 1000, speed: 7.0, jumpForce: 13.8, attackPower: 1.0, defense: 1.0 },
    superType: 'RENOIR_FLOWER',
    visual: {
      coatType: 'draped_overcoat',
      headgear: 'none',
      hairColor: '#2b2927',
      hairStyle: 'gentleman_beard',
      hasMustache: true,
      hasCane: true,
      maskStyle: 'none',
      coatColor: '#0a0a0c',
      accentColor: '#94a3b8',
      vestColor: '#1e293b',
      pantColor: '#090808',
      bootColor: '#1c1917',
      gloveColor: '#1c1917',
      paintTrailColor: '#f59e0b',
      weaponType: 'gentleman_cane'
    },
    description: 'Pai de Verso. Traje nobre clássico com sobretudo sobre os ombros, bengala de ferro e ataques impiedosos.'
  },
  {
    id: 106,
    name: 'Verso',
    image: './assets/expedition33/verso.png',
    themeColor: '#6366f1',
    secondaryColor: '#4338ca',
    glowColor: 'rgba(99, 102, 241, 0.85)',
    energyColor: '#c7d2fe',
    stats: { health: 1000, speed: 7.0, jumpForce: 13.8, attackPower: 1.0, defense: 1.0 },
    isVerso: true,
    hasNoSkills: true,
    visual: {
      coatType: 'fur_collar_coat',
      headgear: 'none',
      hairColor: '#18181b',
      hairStyle: 'white_streak_fringe',
      hasMustache: true,
      hasFurCollar: true,
      maskStyle: 'none',
      coatColor: '#09090b',
      accentColor: '#d4af37',
      vestColor: '#18181b',
      pantColor: '#09090b',
      bootColor: '#18181b',
      gloveColor: '#1e1b4b',
      paintTrailColor: '#818cf8',
      weaponType: 'gold_saber'
    },
    description: 'Sobrevivente da 1ª Expedição. Cabelos negros com mecha branca frontal, casaco com gola de pele e sabre dourado cintilante.'
  },
  {
    id: 107,
    name: 'Monoco',
    image: './assets/expedition33/monoco.png',
    themeColor: '#d97706',
    secondaryColor: '#78350f',
    glowColor: 'rgba(217, 119, 6, 0.85)',
    energyColor: '#fef3c7',
    stats: { health: 1000, speed: 7.0, jumpForce: 13.8, attackPower: 1.0, defense: 1.0 },
    visual: {
      coatType: 'stone_shell',
      headgear: 'none',
      hairColor: '#cbd5e1',
      hairStyle: 'white_fur_mane',
      hasMustache: false,
      hasRuneFaceSlab: true,
      hasStaffBell: true,
      maskStyle: 'none',
      coatColor: '#475569',
      accentColor: '#f59e0b',
      vestColor: '#334155',
      pantColor: '#1e293b',
      bootColor: '#0f172a',
      gloveColor: '#d97706',
      paintTrailColor: '#f59e0b',
      weaponType: 'gestral_staff',
      isMonoco: true
    },
    superType: 'MONOCO_PARRY_MIMIC',
    description: 'Gestral guardião. Corpo pétreo coberto por pelos brancos, monólito gravado como rosto e cajado com sino de bronze.'
  },
  {
    id: 109,
    name: 'La Peintresse',
    image: './assets/expedition33/la_peintresse.png',
    themeColor: '#fbbf24',
    secondaryColor: '#d97706',
    glowColor: 'rgba(251, 191, 36, 0.95)',
    energyColor: '#ffffff',
    stats: { health: 1000, speed: 7.0, jumpForce: 13.8, attackPower: 1.0, defense: 1.0 },
    visual: {
      coatType: 'baroque_gown',
      headgear: 'halo_mask',
      hairColor: '#09090b',
      hairStyle: 'baroque_updo',
      hasMustache: false,
      maskStyle: 'full_porcelain_halo',
      coatColor: '#09090b',
      accentColor: '#fbbf24',
      vestColor: '#18181b',
      pantColor: '#09090b',
      bootColor: '#09090b',
      gloveColor: '#fbbf24',
      paintTrailColor: '#fbbf24',
      weaponType: 'colossal_brush',
      isPaintress: true
    },
    superType: 'PAINTRESS_CHROMATIC_WAVES',
    description: 'A deusa misteriosa que acorda a cada ano para pintar um número no Monólito e apagar toda uma geração. Luta com um pincel monumental e arcos de tinta viva.'
  },
  {
    id: 110,
    name: 'Batman',
    image: './assets/expedition33/batman.jpg',
    themeColor: '#38bdf8',
    secondaryColor: '#0f172a',
    glowColor: 'rgba(56, 189, 248, 0.85)',
    energyColor: '#e2e8f0',
    stats: { health: 1000, speed: 7.0, jumpForce: 13.8, attackPower: 1.0, defense: 1.0 },
    superType: 'BATMAN_BATMOBILE',
    visual: {
      coatType: 'capelet',
      headgear: 'bat_cowl',
      hairColor: '#09090b',
      hairStyle: 'none',
      hasMustache: false,
      maskStyle: 'bat_cowl',
      coatColor: '#09090b',
      accentColor: '#38bdf8',
      vestColor: '#1e293b',
      pantColor: '#0f172a',
      bootColor: '#09090b',
      gloveColor: '#0f172a',
      paintTrailColor: '#38bdf8',
      weaponType: 'batarang'
    },
    description: 'O Cavaleiro das Trevas de Gotham adaptado à expedição. Luta com artes marciais furtivas, batarangues e atropela com o Batmóvel enquanto salta com um mortal acrobático.'
  },
  {
    id: 111,
    name: 'Darth Vader',
    image: './assets/expedition33/darth_vader.jpg',
    themeColor: '#ef4444',
    secondaryColor: '#09090b',
    glowColor: 'rgba(239, 68, 68, 0.9)',
    energyColor: '#fca5a5',
    stats: { health: 1000, speed: 7.0, jumpForce: 13.8, attackPower: 1.0, defense: 1.0 },
    superType: 'VADER_CHOKE',
    visual: {
      coatType: 'draped_overcoat',
      headgear: 'sith_helmet',
      hairColor: '#09090b',
      hairStyle: 'none',
      hasMustache: false,
      maskStyle: 'sith_respirator',
      coatColor: '#050505',
      accentColor: '#ef4444',
      vestColor: '#18181b',
      pantColor: '#09090b',
      bootColor: '#050505',
      gloveColor: '#18181b',
      paintTrailColor: '#ef4444',
      weaponType: 'sith_lightsaber'
    },
    description: 'O temido Lorde Sith empunhando seu sabre de luz escarlate e canalizando a Força para estrangular e arremessar seus inimigos.'
  },
  {
    id: 112,
    name: 'Palpatine',
    image: './assets/expedition33/palpatine.jpg',
    themeColor: '#a855f7',
    secondaryColor: '#18181b',
    glowColor: 'rgba(168, 85, 247, 0.9)',
    energyColor: '#c084fc',
    stats: { health: 1000, speed: 7.0, jumpForce: 13.8, attackPower: 1.0, defense: 1.0 },
    superType: 'PALPATINE_DUAL_SABERS',
    visual: {
      coatType: 'mantle',
      headgear: 'hood',
      hairColor: '#e2e8f0',
      hairStyle: 'none',
      hasMustache: false,
      maskStyle: 'shadow_veil',
      coatColor: '#18181b',
      accentColor: '#a855f7',
      vestColor: '#09090b',
      pantColor: '#09090b',
      bootColor: '#09090b',
      gloveColor: '#3b0764',
      paintTrailColor: '#c084fc',
      weaponType: 'force_lightning'
    },
    description: 'O Imperador das Sombras conjurando torrentes de raios da Força e desferindo um violento turbilhão com dois sabres de luz soltando faíscas no chão.'
  },
  {
    id: 113,
    name: 'Coringa',
    image: './assets/expedition33/coringa.jpg',
    themeColor: '#10b981',
    secondaryColor: '#7c3aed',
    glowColor: 'rgba(16, 185, 129, 0.85)',
    energyColor: '#f43f5e',
    stats: { health: 1000, speed: 7.0, jumpForce: 13.8, attackPower: 1.0, defense: 1.0 },
    superType: 'JOKER_CROWBAR',
    visual: {
      coatType: 'trenchcoat',
      headgear: 'fedora',
      hairColor: '#16a34a',
      hairStyle: 'messy_bangs',
      hasMustache: false,
      maskStyle: 'clown_smile',
      coatColor: '#581c87',
      accentColor: '#10b981',
      vestColor: '#047857',
      pantColor: '#3b0764',
      bootColor: '#18181b',
      gloveColor: '#7c3aed',
      paintTrailColor: '#10b981',
      weaponType: 'clown_cards'
    },
    description: 'O Palhaço do Crime com Cartas do Caos cortantes em leque e espancamento cômico com pé de cabra.'
  },
  {
    id: 114,
    name: 'Jack Sparrow',
    image: './assets/expedition33/jack_sparrow.jpg',
    themeColor: '#f59e0b',
    secondaryColor: '#78350f',
    glowColor: 'rgba(245, 158, 11, 0.85)',
    energyColor: '#fef3c7',
    stats: { health: 1000, speed: 7.0, jumpForce: 13.8, attackPower: 1.0, defense: 1.0 },
    superType: 'SPARROW_BLACK_PEARL',
    visual: {
      coatType: 'duster',
      headgear: 'tricorne',
      hairColor: '#291b07',
      hairStyle: 'messy_bangs',
      hasMustache: true,
      maskStyle: 'pirate_bandana',
      coatColor: '#451a03',
      accentColor: '#f59e0b',
      vestColor: '#291b07',
      pantColor: '#1c1917',
      bootColor: '#18181b',
      gloveColor: '#78350f',
      paintTrailColor: '#fbbf24',
      weaponType: 'pirate_saber'
    },
    description: 'Capitão Jack Sparrow bebendo rum para esquivas imprevisíveis e bombardeando a arena com salvas de canhão periódicas do Pérola Negra.'
  },
  {
    id: 115,
    name: 'Relâmpago McQueen',
    image: './assets/expedition33/relampago_mcqueen.jpg',
    themeColor: '#ef4444',
    secondaryColor: '#facc15',
    glowColor: 'rgba(239, 68, 68, 0.95)',
    energyColor: '#fde047',
    stats: { health: 1000, speed: 7.0, jumpForce: 13.8, attackPower: 1.0, defense: 1.0 },
    superType: 'MCQUEEN_KACHOW_BLITZ',
    voiceAbility: 'mcqueen_katchau',
    visual: {
      isVehicle: true,
      isMcQueen: true,
      coatType: 'overcoat',
      headgear: 'racer_cap',
      hairColor: '#facc15',
      hairStyle: 'none',
      hasMustache: false,
      maskStyle: 'visor_95',
      coatColor: '#b91c1c',
      accentColor: '#facc15',
      vestColor: '#7f1d1d',
      pantColor: '#18181b',
      bootColor: '#991b1b',
      gloveColor: '#dc2626',
      paintTrailColor: '#facc15',
      weaponType: 'turbo_thrust'
    },
    description: 'O lendário número 95 da Copa Pistão em sua forma autêntica de carro de corrida, queimando pneus com drift e atropelando tudo no Ka-Chow Blitz!'
  }
];

export function getExpeditionCharacterById(id) {
  return EXPEDITION_33_CHARACTERS.find((c) => c.id === Number(id)) || EXPEDITION_33_CHARACTERS[0];
}
